source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

# Pods for RSSReader
target 'RSSReader' do

	# Network
	pod 'AFNetworking', '~> 3.0'
	
	# DataBase
	pod 'MagicalRecord'

	# MVVM Binding
	pod 'KVOController'

end
